### PR TITLE
Add - Ordinal Function

### PR DESCRIPTION
**Pull request by TestSubjector**
Translated the simple Ordinal IDL AstroLib procedure, which returns the English equivalent of ordinal numbers, i.e. '1st','2nd' etc. 
PR for the same.

_Note - Used if-else statements (unlike cases in the original IDL AstroLib procedure) while translating as Julia lacks a C-style switch statement._

### CODE REVIEW

**Comment by giordano** [comment]
Thank you so much for your contribution!  However I have some comments:

* an important point most Julia newcomers aren't familiar with is type-stability: in order to produce efficient code you must be sure that a variable will always keep the same type, see http://docs.julialang.org/en/latest/manual/performance-tips.html#Write-\  Your function takes a `num` argument that is any subtype of `Real` than is converted to `Int`.  You can avoid this issue by assigning this conversion to `a`.  Don't worry, I think that everyone wrote many type-unstable functions before doing it right ;-)  Use `@code_warntype`, it'll be your best friend at the beginning of your Julia trip.

* actually I'm not sure it's useful to take any `Real`, probably a `Integer` suffices here (and the conversion mentioned in the previous point is no more needed, but always mind type-instabilities).  I see that this is how the IDL function works, but try to be smarter than those functions.

* another performance tip is to [avoid string interpolation](http://docs.julialang.org/en/latest/manual/performance-tips.html#Avoid-string-interpolation-for-I/O-1): return `string(num) * suffix` instead.

* please add a test set for the new function, in order to test every possible situation.  It's really important in order to ensure consistency of the results and to avoid that bugs will be accidentally introduced in the future.  I strive to keep code coverage at 100%.

* In addition, with a test you would notice that the function isn't actually included in the library, nor exported: see the file `src/utils.jl`.  Admittedly, I'm not particularly proud of the code is organized right now, it may change in the future, but this is how it works now.

Another, minor, stylistic comment: please remove trailing whitespaces.

I think this is enough.  Are you able to fix everything y yourself?  Anyway, that was a good start!

**Comment by TestSubjector** [comment]
Thank you for the detailed reply.

- You're correct, I wasn't aware of the type-stability and the performance tips. I'll be sure to go through that.

- I kept the conversion so as to keep it similar to the structure of the IDL procedure, which I assumed (incorrectly) was a rigid rule to follow.

- I noticed the purpose of the src/utils.jl file, but I didn't want to modify it until I got a review on this commit. 

I'll make the necessary changes including the test set. 
Thanks again for the help.

**Comment by giordano** [comment]
> I kept the conversion so as to keep it similar to the structure of the IDL procedure, which I assumed (incorrectly) was a rigid rule to follow.

No, it's not necessary to closely follow the original implementation.  Well, I mostly did so, but the important is to obtain exact results paying attention to performance.

> Should I add those changes as further commits on this branch or create a new PR?

Just keep editing your branch (you can either amend the commit or push new changes), this PR will be updated, no need to open a new one.

Thanks!

**Comment by giordano** [comment]
Only another comment: `Int` is not the same thing as `Integer`, see http://docs.julialang.org/en/latest/manual/integers-and-floating-point-numbers.html.  `Int` is a concrete type that defaults to `Int32` in 32-bit systems and `Int64` in 64-bit systems, but in general we want the functions to be as loosely typed as possible, so abstract types should be preferred ;-)

**Comment by giordano** [comment]
I installed a few minor changes related to the organization of the code and merged the PR.  Thanks!

**Comment by TestSubjector** [comment]
Thanks, I'll make a note of the changes for future PRs

**Pull request merged**
