### PR TITLE
[WIP] Use static arrays

### LINKED ISSUE #45: Use StaticArrays
In most cases, we know in advance the size of the vectors or matrices created and they won't be changed afterwards.  Therefore, it's a good idea to use `StaticArrays` for those arrays.

### PR DESCRIPTION
**Pull request by giordano**
Fix #45.

This is marked as work-in-progress because I'm not sure I made all possible changes.  Feel free to report any missing array to change.

### CODE REVIEW

**Comment by TestSubjector** [comment]
Perhaps the following changes?

In [bprecess.jl](https://github.com/JuliaAstro/AstroLib.jl/blob/078c4be86de92da44b12f0eeda31cf1d998abec5/src/bprecess.jl#L42), change line 42 to
```julia
s = Vector{T}(s1)
```

Additionally, since `premat()` returns an array; either convert it to static or convert the variable that receives the return value of premat (in [precess.jl](https://github.com/JuliaAstro/AstroLib.jl/pull/46/files#diff-5df160f272f9796392a527af64a191e7L17) and [baryvel.jl](https://github.com/JuliaAstro/AstroLib.jl/blob/078c4be86de92da44b12f0eeda31cf1d998abec5/src/baryvel.jl#L227)) to static?

**Comment by giordano** [comment]
Thanks for looking into it!

> In bprecess.jl, change line 42 to
> 
> ```julia
> s = Vector{T}(s1)
> ```

`s` will be changed, doing what you suggest would change `s1` as well, this is what I wanted to avoid with the copy.  See this example:
```julia
julia> s = randn(3)
3-element Array{Float64,1}:
  0.593006
 -1.79782 
  0.592398

julia> s1 = Vector{Float64}(s)
3-element Array{Float64,1}:
  0.593006
 -1.79782 
  0.592398

julia> s1[1] = -5
-5

julia> s
3-element Array{Float64,1}:
 -5.0     
 -1.79782 
  0.592398
```

> Additionally, since premat() returns an array; either convert it to static or convert the variable that receives the return value of premat (in precess.jl and baryvel.jl) to static?

Not sure what you refer to, the PR already makes the array returned by `premat` static: https://github.com/JuliaAstro/AstroLib.jl/pull/46/files#diff-3466cd565556cdaaf4ea10f869aa4961

**Comment by TestSubjector** [comment]
> Not sure what you refer to, the PR already makes the array returned by premat static: https://github.com/JuliaAstro/AstroLib.jl/pull/46/files#diff-3466cd565556cdaaf4ea10f869aa4961

Ah, didn't notice that. I was referring to the same.

I think almost everything is covered by the PR then.

**Comment by giordano** [comment]
> I think almost everything is covered by the PR then.

I don't expect to have covered *everything*, but almost everything is a good result :-)  Thanks!

**Comment by giordano** [comment]
Holding back the PR because of https://github.com/JuliaArrays/StaticArrays.jl/issues/321 which makes `nutate` type-unstable on Julia master.

**Pull request merged**
