### PR TITLE
Add Documenter docs/ directory and make LaTEX edits

### PR DESCRIPTION
**Pull request by cormullion**
This branch basically moves the old `docs/` directory to `docs-rst/` and adds a new `docs` folder that builds a Documenter.jl set of HTML pages. I also changed some of the LaTEX code in the `src/` directory, because Documenter prefers ` `` ..`` ` to `\$` format. 

What's left to do is make the `gh-pages` branch and do the [Travis integration and deployment](https://juliadocs.github.io/Documenter.jl/latest/man/hosting.html) which you have to do, as owner, I think. (Michael is very helpful on [gitter](https://gitter.im/juliadocs/users)...!)

### CODE REVIEW

**Comment by giordano** [comment]
Thank you!  Could you please rebase the patch on master?

Wow, there is a logo now, cool! :-)

**Comment by cormullion** [comment]
Er, OK. Can you tell me what I have to type (I don't get `rebase`):

```
[~/.julia/v0.5/AstroLib] $ git status
On branch documenter
nothing to commit, working tree clean
[~/.julia/v0.5/AstroLib] $ git remote -v
origin	https://github.com/cormullion/AstroLib.jl.git (fetch)
origin	git@github.com:JuliaAstro/AstroLib.jl.git (push)
upstream	https://github.com/cormullion/AstroLib.jl.git (fetch)
upstream	https://github.com/cormullion/AstroLib.jl.git (push)
```

**Comment by giordano** [comment]
My understanding is that you based the patch on a branch, namely `julia-0.5`, which diverged from master.

You could try this:
```
git rebase master
```
and fix the conflicts (essentially `REQUIRE`, `Compat` is not required in master).  But I'd suggest repeating the patch basing it on master.

This is a good introduction to rebasing with git: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by giordano** [comment]
It's pretty easy for me to cherry-pick your change and apply it locally, than push the commit to the repository.

Please tell me if you prefer trying fixing this PR, otherwise I'll do as described above.

**Comment by cormullion** [comment]
I have an uncanny ability to screw things up when using git, so if you can do things more predictably that would be great!

**Comment by giordano** [comment]
Don't worry, we fixed it easily anyway ;-)

Thank you, I'll see what I need to do on my side to deploy the documentation.

**Comment by giordano** [comment]
@cormullion I'm studying documentation of Documenter.  [Here](https://juliadocs.github.io/Documenter.jl/stable/man/guide.html) it's written:

> **Never** `git commit` the contents of `build` (or any other content generated by Documenter) to your repository's `master` branch.

I guess I can remove that directory, right?

**Comment by cormullion** [comment]
Yes, I think eventually the building goes on in the gh-pages branch and only the docs/src is updated on the master branch. It's hard to set it up in a forked branch.

**Pull request closed without merging**
